name: notifications
description: A plugin for tracking notifications on the device. Works exclusively for Android.
version: 2.0.1
homepage: https://github.com/cph-cachet/flutter-plugins/tree/master/packages/notifications

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.3.4"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  

plugin:
    platforms:
      android:
        package: dk.cachet.notifications
        pluginClass: NotificationsPlugin
      ios:
        pluginClass: NotificationsPlugin